Payment gateway
ricgomez99/Tech-e.commerce pull request #82
Opened 2022-11-29 22:10 UTC by martinagirollet

2022-11-29 23:52 UTC, juanjobogado approved these changes

2022-11-30 15:10 UTC, ricgomez99 requested changes
function cardPayment should be written in Pascal (CardPayment).

2022-11-30 18:10 UTC, ricgomez99 requested changes
Agrega un key a la iteración del products.items

2022-11-30 18:16 UTC, ricgomez99 approved these changes

2022-11-30 18:16 UTC, merged